---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  rewrite.conf: |
    server {
      listen 8080;
    
      location / {
        add_header uri $uri;
        index /index.txt;
        try_files $uri /index.txt;
      }
    }