---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  rewrite.conf: |
    server {
      listen 8080;
      server_name *.kigawa.net;
    
      location / {
        root /usr/share/nginx/html;
        add_header uri $uri;
        index /index.html;
        try_files $uri /index.html;
      }
    }