
---
apiVersion: v1
kind: Service
metadata:
  name: hazakura
spec:
  selector:
    app: hazakura
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: "http"
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hazakura-ingress
spec:
  ingressClassName: haproxy
  rules:
    - host: hazakura-test.kigawa.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hazakura
                port:
                  number: 8080
