---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-web
  template:
    metadata:
      labels:
        app: backend-web
    spec:
      containers:
        - name: backend-web
          ports:
            - containerPort: 8080
          image: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
      volumes:
        - name: config
          configMap:
            name: back-nginx-config
